services:
  frontend:
    user: "${DOCKER_FRONTEND_UID:-1000}:${DOCKER_FRONTEND_GID:-1000}"
    build:
      context: ./frontend
      target: dev
    volumes:
      - ./frontend:/usr/src/app
    # command: -c "bun --bun run ./build/index.js"
    command: -c "bun --bun run dev --host"

